version: "1.1"

services:

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 4001:4001

  frontend:
    container_name: frontend_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 4174:5173

  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: api_user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - 3306:3306
    networks:
      - backend
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

networks:
  backend:
    driver: bridge
